import type { Metadata } from "next";
import { DM_Sans, DM_Serif_Display } from "next/font/google";
import "./globals.css";
import { CartProvider } from "@/components/cart/CartProvider";
import { CartButton } from "@/components/cart/CartButton";
import { CartSidebar } from "@/components/cart/CartSidebar";
import { AuthSessionProvider } from "@/components/auth/AuthSessionProvider";
import GlobalNavbar from "@/components/common/GlobalNavbar";
import Footer from "@/components/common/Footer";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const dmSerif = DM_Serif_Display({
  variable: "--font-dm-serif",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} ${dmSerif.variable} antialiased`}
      >
        <AuthSessionProvider>
          <GlobalNavbar  />
          <CartProvider>
            {children}
            <CartButton />
            <CartSidebar />
          </CartProvider>
          <Footer />
        </AuthSessionProvider>
      </body>
    </html>
  );
}
