'use client';

import React, { useState, useEffect } from 'react';
import { Sparkles, RefreshCw, Download, AlertCircle } from 'lucide-react';
import { useSession } from 'next-auth/react';
import toast from 'react-hot-toast';

interface AICakePreviewProps {
  name: string;
  flavor: string;
  size: string;
  toppings: string[];
  frosting: string;
  message: string;
  cakeId?: string;
}

export default function AICakePreview({
  name,
  flavor,
  size,
  toppings,
  frosting,
  message,
  cakeId,
}: AICakePreviewProps) {
  const { data: session } = useSession();
  const [imageUrl, setImageUrl] = useState<string>('');
  const [loading, setLoading] = useState(false);
  const [showPreview, setShowPreview] = useState(false);
  const [imageError, setImageError] = useState(false);
  const [generationCount, setGenerationCount] = useState(0);
  const [remaining, setRemaining] = useState<number | null>(null);
  const [limitError, setLimitError] = useState<string>('');
  const [usageInfo, setUsageInfo] = useState<string>('');

  const generateCakeImage = async () => {
    if (!session) {
      toast.error('Please sign in to generate cake images');
      return;
    }

    // Build a single prompt string for the new endpoint
    const promptParts = [
      name ? `Cake name: ${name}` : '',
      flavor ? `Flavor: ${flavor}` : '',
      size ? `Size: ${size}` : '',
      toppings && toppings.length > 0 ? `Toppings: ${toppings.join(', ')}` : '',
      frosting ? `Frosting: ${frosting}` : '',
      message ? `Message: ${message}` : '',
    ].filter(Boolean);
    const prompt = promptParts.join('. ');

    if (!prompt) {
      toast.error('Please describe the cake first.');
      return;
    }

    setLoading(true);
    setImageError(false);
    setLimitError('');
    
    try {
      toast.loading('🎨 Generating your cake design... This will take 10-20 seconds', { id: 'cake-gen' });
      
      const response = await fetch('/api/generate-cake', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({ prompt, cakeId }),
      });

      const data = await response.json();

      if (response.ok && data.imageUrl) {
        setImageUrl(data.imageUrl);
        setShowPreview(true);
        setGenerationCount(prev => prev + 1);
        if (data.remaining !== undefined) {
          setRemaining(data.remaining);
        }
        if (data.usageInfo) {
          setUsageInfo(data.usageInfo);
        }
        toast.success('🎉 Cake design generated!', { id: 'cake-gen' });
      } else {
        toast.dismiss('cake-gen');
        if (response.status === 429) {
          // Rate limit hit
          setLimitError(data.error || 'Generation limit reached');
          setRemaining(0);
          toast.error(data.error || "You've reached your generation limit");
        } else {
          setImageError(true);
          toast.error(data.error || 'Failed to generate cake image');
        }
      }
    } catch (error) {
      toast.dismiss('cake-gen');
      console.error('Error generating cake image:', error);
      setImageError(true);
      toast.error('Error generating cake image. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const downloadImage = async () => {
    if (!imageUrl) return;
    
    try {
      toast.loading('Downloading image...', { id: 'download' });
      const response = await fetch(imageUrl, {
        mode: 'no-cors'
      });
      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${name.replace(/\s+/g, '-')}-cake.png`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
      toast.success('Image downloaded successfully!', { id: 'download' });
    } catch (error) {
      toast.dismiss('download');
      console.error('Error downloading image:', error);
      toast.error('Failed to download image');
    }
  };

  const isLimitReached = remaining === 0;

  return (
    <div className="space-y-6 py-8 border-t border-[#1a1a1a]/10">
      <div className="space-y-4">
        <div className="flex items-center gap-3">
          <Sparkles className="w-6 h-6 text-pink-500" />
          <h3 className="font-bold text-xs uppercase tracking-widest text-gray-500">
            AI-Generated Preview
          </h3>
        </div>
        
        <p className="text-sm text-gray-600">
          {showPreview && imageUrl
            ? 'Here\'s your personalized cake design generated by AI'
            : 'Generate a preview of your customized cake with the selected options'}
        </p>

        {/* Customization Summary */}
        <div className="bg-[#FFF9EB]/50 border border-[#1a1a1a]/10 p-4 rounded-lg text-sm space-y-2">
          <p><span className="font-semibold">Cake:</span> {name}</p>
          <p><span className="font-semibold">Flavor:</span> {flavor}</p>
          <p><span className="font-semibold">Size:</span> {size}</p>
          {frosting && <p><span className="font-semibold">Frosting:</span> {frosting}</p>}
          {toppings.length > 0 && (
            <p><span className="font-semibold">Toppings:</span> {toppings.join(', ')}</p>
          )}
          {message && <p><span className="font-semibold">Message:</span> "{message}"</p>}
        </div>

        {/* Generate Button */}
        {!showPreview && (
          <button
            onClick={generateCakeImage}
            disabled={loading || isLimitReached}
            className="w-full bg-pink-500 text-white py-4 font-bold uppercase tracking-widest text-sm flex items-center justify-center gap-3 hover:bg-pink-600 transition-all disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <Sparkles className="w-5 h-5" />
            {loading ? 'Generating Your Design...' : 'Generate AI Preview'}
          </button>
        )}

        {/* Usage Info */}
        {remaining !== null && (
          <div className={`p-3 rounded-lg text-sm ${isLimitReached ? 'bg-red-50 border border-red-200' : 'bg-blue-50 border border-blue-200'}`}>
            <p className={isLimitReached ? 'text-red-700 font-semibold' : 'text-blue-700'}>
              {usageInfo || `Generations remaining: ${remaining}`}
            </p>
          </div>
        )}

        {/* Limit Error */}
        {limitError && (
          <div className="bg-red-50 border border-red-200 p-4 rounded-lg flex gap-3">
            <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
            <div>
              <h4 className="font-semibold text-red-900 text-sm mb-1">Generation Limit Reached</h4>
              <p className="text-sm text-red-700">{limitError}</p>
            </div>
          </div>
        )}
      </div>

      {/* Image Preview */}
      {showPreview && imageUrl && !imageError && (
        <div className="space-y-4">
          <div className="bg-white border border-[#1a1a1a]/10 rounded-lg overflow-hidden relative">
            <div className="w-full bg-gray-100 flex items-center justify-center" style={{ minHeight: '400px' }}>
              <img
                src={imageUrl}
                alt={`${name} - AI Generated Preview`}
                className="w-full h-auto object-cover max-h-96"
                onError={() => setImageError(true)}
                onLoad={() => setImageError(false)}
                crossOrigin="anonymous"
              />
            </div>
          </div>

          <div className="flex gap-3">
            <button
              onClick={generateCakeImage}
              disabled={loading}
              className="flex-1 bg-[#1a1a1a] text-[#F7E47D] py-3 font-bold uppercase tracking-widest text-sm flex items-center justify-center gap-2 hover:bg-black transition-all disabled:opacity-50"
            >
              <RefreshCw className="w-4 h-4" />
              Regenerate
            </button>
            
            <button
              onClick={downloadImage}
              className="flex-1 bg-gray-100 text-[#1a1a1a] py-3 font-bold uppercase tracking-widest text-sm flex items-center justify-center gap-2 hover:bg-gray-200 transition-all"
            >
              <Download className="w-4 h-4" />
              Download
            </button>
          </div>
        </div>
      )}

      {/* Loading State */}
      {showPreview && loading && (
        <div className="bg-gray-50 border border-[#1a1a1a]/10 p-8 rounded-lg text-center">
          <div className="flex justify-center mb-4">
            <div className="animate-spin">
              <Sparkles className="w-8 h-8 text-pink-500" />
            </div>
          </div>
          <p className="text-sm text-gray-600">Generating your personalized cake design...</p>
        </div>
      )}

      {/* Error State */}
      {(imageError || (showPreview && !imageUrl && !loading)) && (
        <div className="bg-red-50 border border-red-200 p-6 rounded-lg space-y-4">
          <div className="flex gap-3">
            <AlertCircle className="w-5 h-5 text-red-600 flex-shrink-0 mt-0.5" />
            <div>
              <h4 className="font-semibold text-red-900 mb-2">Image Generation Failed</h4>
              <p className="text-sm text-red-700 mb-4">
                The image generation service is experiencing issues. Please try regenerating or try again in a moment.
              </p>
              <button
                onClick={generateCakeImage}
                disabled={loading}
                className="w-full bg-red-600 text-white py-2 px-4 rounded font-medium text-sm hover:bg-red-700 transition-all disabled:opacity-50"
              >
                {loading ? 'Retrying...' : 'Try Again'}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
